import type { VideoIdea } from '@/types/database'

export const mockIdeas: VideoIdea[] = [
  {
    id: 1,
    title: 'Je teste TOUS les McDo du monde en 24h',
    format_tag: 'challenge',
    source: 'ai',
    rationale: 'Les vidéos challenge McDo performent 3x au-dessus de la moyenne. Fort potentiel viral avec le concept mondial.',
    estimated_views: 5_000_000,
    is_long_form: true,
    status: 'approved',
    created_at: '2026-03-15T10:00:00Z',
  },
  {
    id: 2,
    title: 'La street food la plus DANGEREUSE du Mexique',
    format_tag: 'vlog',
    source: 'trend',
    rationale: 'Tendance street food exotique en hausse de 180% sur TikTok. Contenu immersif très engageant.',
    estimated_views: 3_500_000,
    is_long_form: true,
    status: 'backlog',
    created_at: '2026-03-14T14:30:00Z',
  },
  {
    id: 3,
    title: 'Réaction aux PIRES recettes de Gordon Ramsay',
    format_tag: 'reaction',
    source: 'comment',
    rationale: 'Demandé par 200+ commentaires. Les réactions Gordon Ramsay font toujours du chiffre.',
    estimated_views: 4_200_000,
    is_long_form: true,
    status: 'approved',
    created_at: '2026-03-13T09:15:00Z',
  },
  {
    id: 4,
    title: 'Bento magique en 45 secondes',
    format_tag: 'short',
    source: 'trend',
    rationale: 'Le format bento explose sur TikTok. Facile à produire et fort taux de partage.',
    estimated_views: 800_000,
    is_long_form: false,
    status: 'backlog',
    created_at: '2026-03-12T16:45:00Z',
  },
  {
    id: 5,
    title: 'Je cuisine avec un robot IA pendant 24h',
    format_tag: 'challenge',
    source: 'ai',
    rationale: 'Croiser la tendance IA + food = format unique. Potentiel de buzz énorme.',
    estimated_views: 6_000_000,
    is_long_form: true,
    status: 'backlog',
    created_at: '2026-03-11T11:20:00Z',
  },
  {
    id: 6,
    title: 'Tuto : le ramen parfait en 10 minutes',
    format_tag: 'tuto',
    source: 'manual',
    rationale: 'Ramen = mot-clé très recherché. Recette accessible + format tutoriel evergreen.',
    estimated_views: 2_000_000,
    is_long_form: true,
    status: 'approved',
    created_at: '2026-03-10T08:00:00Z',
  },
  {
    id: 7,
    title: 'Le croissant parfait en 30 sec',
    format_tag: 'short',
    source: 'competitor',
    rationale: 'Concurrent principal a fait 2M vues avec un format similaire. On peut faire mieux.',
    estimated_views: 1_200_000,
    is_long_form: false,
    status: 'rejected',
    created_at: '2026-03-09T13:30:00Z',
  },
  {
    id: 8,
    title: 'J\'infiltre la cuisine d\'un palace 5 étoiles',
    format_tag: 'vlog',
    source: 'manual',
    rationale: 'Contenu exclusif type "behind the scenes" qui fidélise l\'audience.',
    estimated_views: 3_800_000,
    is_long_form: true,
    status: 'backlog',
    created_at: '2026-03-08T10:45:00Z',
  },
  {
    id: 9,
    title: 'Dégustation aveugle : 1€ vs 1000€',
    format_tag: 'challenge',
    source: 'ai',
    rationale: 'Le format "prix extrême" est un classique BATTELLS avec un CTR moyen de 12%.',
    estimated_views: 7_500_000,
    is_long_form: true,
    status: 'approved',
    created_at: '2026-03-07T15:00:00Z',
  },
  {
    id: 10,
    title: 'Les secrets du chocolat bean-to-bar',
    format_tag: 'tuto',
    source: 'trend',
    rationale: 'Dubai chocolate trend + tuto = combo gagnant pour le SEO.',
    estimated_views: 1_800_000,
    is_long_form: true,
    status: 'backlog',
    created_at: '2026-03-06T09:30:00Z',
  },
  {
    id: 11,
    title: 'Je mange comme un sumo pendant 1 semaine',
    format_tag: 'challenge',
    source: 'comment',
    rationale: 'Sujet demandé en masse. Format immersif qui booste le watch time.',
    estimated_views: 4_500_000,
    is_long_form: true,
    status: 'rejected',
    created_at: '2026-03-05T12:00:00Z',
  },
  {
    id: 12,
    title: 'Tacos fusion franco-mexicain',
    format_tag: 'short',
    source: 'competitor',
    rationale: 'Format court recette fusion = partage facile. Cible nouvelle audience.',
    estimated_views: 600_000,
    is_long_form: false,
    status: 'backlog',
    created_at: '2026-03-04T17:15:00Z',
  },
]
