import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const GEMINI_API_KEY = Deno.env.get('GEMINI_API_KEY')!
const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!

const GEMINI_URL = `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-image-preview:generateContent?key=${GEMINI_API_KEY}`

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization, apikey',
}

// Single compressed Baptiste reference (62KB vs 853KB) to avoid Edge Function timeout
const BAPTISTE_PHOTO_URL = 'https://dashboard-battells.netlify.app/baptiste/face-closeup-sm.jpg'

// Face identity lock — sent with every Baptiste template
const FACE_LOCK = `FACE IDENTITY: The reference photo shows Baptiste. Reproduce this EXACT person:
- Face shape, jawline, chin: match precisely
- Eyes: blue-grey, same shape and spacing
- Gold/tortoiseshell metal-frame glasses: ALWAYS present, same frame shape
- Hair: dark curly/wavy brown, short sides, volume on top
- Beard: light brown stubble, patchy cheeks, fuller chin
- Skin: fair with slight warmth
The generated person must be immediately recognizable as this individual.`

// Anti-AI detection — appended to EVERY prompt
const ANTI_AI = `CRITICAL PHOTOGRAPHIC REALISM REQUIREMENTS:
This image must be indistinguishable from a real photograph taken by a professional photographer.
- Natural skin texture with pores, fine lines, subtle imperfections, uneven skin tone, visible veins
- Natural lighting falloff with soft penumbra, no perfectly uniform gradients
- Lens imperfections: subtle chromatic aberration at edges, natural vignetting, micro lens flare
- Organic composition: nothing perfectly centered or symmetrically placed
- Film-like noise grain pattern (ISO 400-800 equivalent), not smooth digital rendering
- Natural depth of field with realistic bokeh circles showing lens blade aperture shape
- Fabric texture with realistic creases, wrinkles, lint, and thread detail
- Food with natural irregularities: uneven browning, asymmetric shapes, drip marks, small air bubbles
- Environmental context: dust motes in light beams, condensation, ambient reflections
- Camera metadata feel: slight barrel distortion at wide angle, compression at telephoto
- NO smooth plastic-looking skin, NO perfect symmetry, NO oversaturated colors, NO HDR glow
- NO unnaturally sharp edges, NO floating objects without shadows, NO perfect gradients
The image should look like it was captured with a real camera by a professional photographer, NOT generated by AI.`

const TEMPLATES: Record<string, { prompt: string; needsBaptiste: boolean }> = {
  'food-closeup': {
    needsBaptiste: false,
    prompt: `Hyperrealistic extreme close-up food photograph of {subject}. Caravaggio-style dramatic chiaroscuro lighting: single warm key light from upper left creating deep shadows and golden highlights. Ingredients glistening with moisture droplets, visible steam rising in backlight. Phase One IQ4 150MP, Schneider 120mm macro at f/2.8, focus stacked. Dark moody negative-fill background. Professional food styling with micro-herbs and sauce artistry. Color temp 3200K tungsten with 5600K rim. 8K, ultra-detailed textures. No text, no watermark.`,
  },

  'split-before-after': {
    needsBaptiste: false,
    prompt: `Split dual-scene food photograph divided by clean vertical line at center. LEFT: chaotic raw {subject} ingredients scattered on dark granite, flour dust in air, eggshells cracked, overhead flat-lay with harsh direct flash. RIGHT: magnificent finished {subject}, professionally plated on matte black ceramic, garnished with precision, soft diffused strobe, shallow DOF f/1.8, warm 3400K, hero lighting 45 degrees. Stark contrast between halves, readable at thumbnail scale. No text.`,
  },

  'challenge-reaction': {
    needsBaptiste: true,
    prompt: `YouTube thumbnail photograph. Baptiste (the person from the reference photo — reproduce his EXACT face, glasses, hair, beard) making an extremely exaggerated shocked reaction: mouth wide open showing teeth, eyes bulging behind gold-frame glasses, hands on cheeks. Looking at {subject} positioned prominently in lower-right foreground, styled spectacular with steam. Canon R5 Mark II, 35mm f/1.4. Two-light: warm orange key camera-left (#FF6B00), cool blue fill camera-right. Dynamic diagonal composition. Vibrant colors. 1280x720 thumbnail optimized. No text overlay.`,
  },

  'cartoon-recipe': {
    needsBaptiste: false,
    prompt: `Vibrant cartoon illustration of magical cooking scene featuring {subject}. Pixar-meets-Ghibli style with volumetric lighting. Ingredients floating in spiral pattern, cel-shading with specular highlights. Animated utensils (whisk spinning, spoon stirring). Warm orange palette (#FF6B00, #FFB800) with teal accents. Golden sparkle particles and steam trails. Bubbling pot at center with light beams from above. Cheerful, energetic. No text.`,
  },

  'gustavo-scene': {
    needsBaptiste: true,
    prompt: `Cinematic portrait photograph. Baptiste (EXACT face from reference: glasses, curly hair, stubble) dressed as sarcastic French chef: white double-breasted jacket, tall toque blanche. Arms crossed, smug smirk, one eyebrow raised. Standing next to {subject}. Sony A1, 85mm GM f/1.4 at f/2.0, creamy bokeh. Rembrandt lighting: warm key 45 degrees, triangle of light on shadowed cheek. Deep shadows. Warm orange-gold palette. Ultra photorealistic, skin pores and stubble visible. No text.`,
  },

  'blind-order': {
    needsBaptiste: true,
    prompt: `Cinematic suspense photograph. Baptiste (EXACT face from reference: gold glasses, curly brown hair, stubble) wearing black silk blindfold OVER glasses, hands hovering over two polished silver cloches on dark mahogany table. One cloche partially lifted revealing {subject} with steam. Low atmospheric fog. Blue-gelled backlight, warm amber key from below (candles), question marks in background with blur. Teal-orange cinematic grade. ARRI Alexa Mini, Cooke 50mm anamorphic, oval bokeh. No text.`,
  },

  'food-explosion': {
    needsBaptiste: false,
    prompt: `Ultra-high-speed freeze-frame food explosion of {subject}. Every ingredient suspended mid-air: leaves mid-curl, sauce droplets as perfect spheres, cheese stretching mid-pull. Phantom Flex4K at 10,000fps equivalent, Nikon 105mm f/2.8 macro. Three lights: powerful backlight for translucent edges, fill from below, subtle key. Pure black background. Ingredients at different depth planes. Sauce droplets catching light like amber jewels. Maximum sharpness. No text.`,
  },

  'text-bold': {
    needsBaptiste: false,
    prompt: `Bold typographic poster. "{title}" in massive 3D brushstroke letters with visible bristle texture. Orange-to-gold gradient (#FF6B00 to #FFB800) with metallic specular highlights. Dynamic stacked composition with slight rotation. Food ({subject}) scattered between letters, some overlapping. Dark charcoal background (#1A1A1A) with bokeh particles (embers, dust motes). Cinematic rim light on letter edges. Social media vertical composition.`,
  },

  'comparison': {
    needsBaptiste: true,
    prompt: `Split comparison photograph. Baptiste (EXACT face from reference: gold glasses, curly hair, stubble) at center with amazed jaw-dropped expression, dividing two versions of {subject}. LEFT: rustic homemade on wooden board with checkered napkin, flat lighting. RIGHT: extravagant restaurant on black slate with gold leaf, dramatic studio lighting. Large "VS" in center with fire and ember effects. Canon R5, 24-70 f/2.8 at 35mm. Ultra photorealistic. No other text.`,
  },

  'cinematic-plate': {
    needsBaptiste: false,
    prompt: `Cinematic bird's-eye-view of {subject} on dark slate plate with raw stone edges. Professional styling: strategic negative space, golden ratio spiral composition, micro-herbs with tweezers, sauce swoosh. Soft overhead key with lens flare from candle at edge. Tilt-shift DOF effect. Anamorphic horizontal flare. Kodak Portra 400 grain. Warm color temp, cool shadow tones. Bon Appetit editorial quality. Dark oak table with patina. No text, no hands.`,
  },

  'defi-24h': {
    needsBaptiste: true,
    prompt: `Dynamic YouTube thumbnail. Baptiste (EXACT face from reference: gold glasses, curly hair, stubble) looking exhausted but determined: sweat on forehead, sleeves rolled up, disheveled hair, dark circles but fierce glint in eyes. Massive industrial clock face in background, food items replacing hour numbers. Clock hands are crossed fork and knife. "24H" in weathered metal typography with orange LED glow (#FF6B00). Surrounded by {subject}. Low-angle hero shot. Ultra photorealistic. No other text.`,
  },

  'street-food': {
    needsBaptiste: false,
    prompt: `Cinematic street photography of French market stall at golden hour. Vendor preparing {subject}: hands in motion with natural blur at 1/30s, steam through golden backlight creating volumetric rays. Leica M11, Summilux 35mm f/1.4 wide open, dreamy DOF. French market signage soft in background. Warm Kodachrome palette. {subject} sharp at center. Cobblestone, stone buildings, copper pots. No text.`,
  },

  'ultra-photorealistic': {
    needsBaptiste: true,
    prompt: `Ultra-photorealistic YouTube thumbnail portrait. Baptiste (EXACT face from reference: blue-grey eyes, gold glasses, curly brown hair, stubble, fair skin) reacting dramatically to {subject}. Sony A7IV, 85mm f/1.4 GM wide open. Three-point lighting: warm key 45deg (3200K octabox), cool fill opposite 30deg (5600K), strong rim/hair light behind-above. Skin fully resolved: pores, stubble, glasses reflections, catchlights in both eyes. {subject} in foreground at f/1.4 bokeh, styled with steam and caramelization. Cinematic grade: lifted blacks, warm highlights, teal shadows. 8K. No text.`,
  },
}

async function fetchBaptistePhoto(): Promise<{ base64: string; mimeType: string } | null> {
  try {
    const res = await fetch(BAPTISTE_PHOTO_URL)
    if (!res.ok) { console.error('Failed to fetch Baptiste photo:', res.status); return null }
    const buffer = await res.arrayBuffer()
    const bytes = new Uint8Array(buffer)
    let binary = ''
    for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i])
    console.log(`Baptiste ref loaded: ${bytes.length} bytes`)
    return { base64: btoa(binary), mimeType: res.headers.get('content-type') || 'image/jpeg' }
  } catch (e) {
    console.error('Baptiste fetch error:', e)
    return null
  }
}

function getPrompt(templateId: string | undefined, title: string, subject: string, platform: string, customPrompt?: string): { prompt: string; needsBaptiste: boolean } {
  if (customPrompt) return { prompt: customPrompt, needsBaptiste: false }
  const template = templateId ? TEMPLATES[templateId] : undefined
  if (!template) {
    return { prompt: `Professional food photograph of ${subject}, dramatic lighting, cinematic composition, ${platform === 'youtube' ? '16:9' : '9:16'} format. No text.`, needsBaptiste: false }
  }
  return { prompt: template.prompt.replace(/\{title\}/g, title || 'BATTELLS').replace(/\{subject\}/g, subject), needsBaptiste: template.needsBaptiste }
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { headers: CORS_HEADERS })

  try {
    const body = await req.json()
    const { template_id, title = '', subject, platform = 'youtube', custom_prompt, format_tag, quality = '2K', video_idea_id, calendar_item_id } = body

    if (!subject) return new Response(JSON.stringify({ error: 'subject is required' }), { status: 400, headers: CORS_HEADERS })

    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY)
    const { prompt: basePrompt, needsBaptiste } = getPrompt(template_id, title, subject, platform, custom_prompt)

    const aspectRatio = platform === 'youtube' ? '16:9' : '9:16'
    const qualityStr = quality === '4K' ? 'Maximum 4K resolution, extreme detail.' : quality === '2K' ? 'High 2K resolution.' : '1K resolution.'

    // Assemble final prompt with anti-AI detection
    const finalPrompt = `${basePrompt}\n\nAspect ratio: ${aspectRatio}. ${qualityStr}\n\n${ANTI_AI}`

    // Build multimodal parts
    const contentParts: any[] = []

    if (needsBaptiste) {
      const photo = await fetchBaptistePhoto()
      if (photo) {
        contentParts.push({ inlineData: { mimeType: photo.mimeType, data: photo.base64 } })
        contentParts.push({ text: `${FACE_LOCK}\n\n${finalPrompt}` })
        console.log('Multimodal: Baptiste ref (62KB) + prompt')
      } else {
        contentParts.push({ text: finalPrompt })
        console.log('Fallback: text-only (no Baptiste ref)')
      }
    } else {
      contentParts.push({ text: finalPrompt })
    }

    console.log('Template:', template_id, '| Baptiste:', needsBaptiste, '| Quality:', quality)

    const geminiRes = await fetch(GEMINI_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: contentParts }],
        generationConfig: { responseModalities: ['TEXT', 'IMAGE'], responseMimeType: 'text/plain' },
      }),
    })

    if (!geminiRes.ok) {
      const errText = await geminiRes.text()
      console.error('Gemini error:', geminiRes.status, errText.slice(0, 300))
      return new Response(JSON.stringify({ error: `Gemini: ${geminiRes.status}`, details: errText.slice(0, 200) }), { status: 502, headers: CORS_HEADERS })
    }

    const data = await geminiRes.json()
    const parts = data.candidates?.[0]?.content?.parts ?? []
    const imagePart = parts.find((p: any) => p.inlineData)

    if (!imagePart?.inlineData?.data) {
      const txt = parts.find((p: any) => p.text)?.text?.slice(0, 200) || 'Empty'
      console.error('No image:', txt)
      return new Response(JSON.stringify({ error: 'No image generated', details: txt }), { status: 502, headers: CORS_HEADERS })
    }

    const base64Data = imagePart.inlineData.data
    const mime = imagePart.inlineData.mimeType || 'image/png'
    const ext = mime.includes('jpeg') ? 'jpeg' : 'png'
    const fileName = `${new Date().toISOString().slice(0, 10)}/${crypto.randomUUID()}.${ext}`
    const imageBuffer = Uint8Array.from(atob(base64Data), c => c.charCodeAt(0))

    const { error: uploadErr } = await supabase.storage.from('thumbnails').upload(fileName, imageBuffer, { contentType: mime, upsert: false })
    if (uploadErr) {
      console.error('Upload error:', uploadErr)
      return new Response(JSON.stringify({ error: 'Upload failed', details: uploadErr.message }), { status: 500, headers: CORS_HEADERS })
    }

    const { data: { publicUrl } } = supabase.storage.from('thumbnails').getPublicUrl(fileName)

    await supabase.from('thumbnail_generations').insert({
      template_id: template_id || 'custom', title: title || subject, prompt_used: basePrompt,
      platform, aspect_ratio: aspectRatio, image_url: publicUrl, image_path: fileName,
      format_tag: format_tag || null, quality,
      metadata: { model: 'gemini-3.1-flash-image-preview', baptiste_ref: needsBaptiste },
      video_idea_id: video_idea_id || null, calendar_item_id: calendar_item_id || null,
    }).then(({ error }) => { if (error) console.error('DB error:', error) })

    return new Response(JSON.stringify({ image_url: publicUrl, prompt_used: basePrompt, template_id: template_id || 'custom', platform }), {
      headers: { 'Content-Type': 'application/json', ...CORS_HEADERS },
    })
  } catch (err) {
    console.error('Error:', err)
    return new Response(JSON.stringify({ error: 'Internal error', details: String(err) }), { status: 500, headers: CORS_HEADERS })
  }
})
