import type { ContentCalendarItem } from '@/types/database'

export const MOCK_CALENDAR_ITEMS: ContentCalendarItem[] = [
  {
    id: 1,
    title: 'Recette du Ramen de Naruto',
    format_tag: 'tuto',
    is_long_form: true,
    planned_date: '2026-03-05',
    status: 'published',
    youtube_video_id: 'abc123',
    notes: 'Video tres bien recue, 500K vues en 48h',
    platforms: ['youtube', 'tiktok'],
    created_at: '2026-02-20T10:00:00Z',
  },
  {
    id: 2,
    title: 'Degustation aveugle McDo vs Chef',
    format_tag: 'challenge',
    is_long_form: true,
    planned_date: '2026-03-12',
    status: 'editing',
    youtube_video_id: null,
    notes: 'Montage en cours, sortie prevue semaine prochaine',
    platforms: ['youtube'],
    created_at: '2026-03-01T09:00:00Z',
  },
  {
    id: 3,
    title: 'Plus grand Tacos du monde',
    format_tag: 'challenge',
    is_long_form: true,
    planned_date: '2026-03-28',
    status: 'scheduled',
    youtube_video_id: null,
    notes: 'Programme pour samedi 28 mars a 14h',
    platforms: ['youtube', 'tiktok', 'instagram'],
    created_at: '2026-03-10T08:00:00Z',
  },
  {
    id: 4,
    title: 'Donuts des Simpsons IRL',
    format_tag: 'tuto',
    is_long_form: true,
    planned_date: '2026-03-18',
    status: 'filmed',
    youtube_video_id: null,
    notes: 'Tournage termine, rushes a trier',
    platforms: ['youtube'],
    created_at: '2026-03-05T14:00:00Z',
  },
  {
    id: 5,
    title: 'Burger One Piece geant',
    format_tag: 'challenge',
    is_long_form: true,
    planned_date: '2026-04-02',
    status: 'planned',
    youtube_video_id: null,
    notes: 'Ingredients commandes',
    platforms: ['youtube', 'tiktok'],
    created_at: '2026-03-08T11:00:00Z',
  },
  {
    id: 6,
    title: '24h dans un food truck',
    format_tag: 'vlog',
    is_long_form: true,
    planned_date: null,
    status: 'idea',
    youtube_video_id: null,
    notes: 'Trouver un food truck partenaire',
    platforms: ['youtube'],
    created_at: '2026-03-15T16:00:00Z',
  },
  {
    id: 7,
    title: 'Je goute les pires snacks du Japon',
    format_tag: 'reaction',
    is_long_form: false,
    planned_date: '2026-03-08',
    status: 'published',
    youtube_video_id: 'def456',
    notes: null,
    platforms: ['youtube', 'tiktok', 'instagram'],
    created_at: '2026-02-28T10:00:00Z',
  },
  {
    id: 8,
    title: 'Recette secrete du Big Mac',
    format_tag: 'tuto',
    is_long_form: false,
    planned_date: '2026-03-15',
    status: 'published',
    youtube_video_id: 'ghi789',
    notes: 'Short viral 2M vues',
    platforms: ['youtube', 'tiktok'],
    created_at: '2026-03-10T09:00:00Z',
  },
  {
    id: 9,
    title: 'Battle de chefs : pizza maison',
    format_tag: 'collab',
    is_long_form: true,
    planned_date: '2026-03-22',
    status: 'scripted',
    youtube_video_id: null,
    notes: 'Script valide avec le collab',
    platforms: ['youtube'],
    created_at: '2026-03-12T13:00:00Z',
  },
  {
    id: 10,
    title: 'Street food Tokyo a minuit',
    format_tag: 'vlog',
    is_long_form: true,
    planned_date: '2026-04-10',
    status: 'planned',
    youtube_video_id: null,
    notes: 'Voyage prevu debut avril',
    platforms: ['youtube', 'instagram'],
    created_at: '2026-03-14T10:00:00Z',
  },
  {
    id: 11,
    title: 'Test : 100 nuggets en 10 min',
    format_tag: 'challenge',
    is_long_form: false,
    planned_date: '2026-03-20',
    status: 'editing',
    youtube_video_id: null,
    notes: 'Montage rapide pour short',
    platforms: ['youtube', 'tiktok'],
    created_at: '2026-03-16T11:00:00Z',
  },
  {
    id: 12,
    title: 'Podcast #12 avec un chef etoile',
    format_tag: 'podcast',
    is_long_form: true,
    planned_date: '2026-04-05',
    status: 'planned',
    youtube_video_id: null,
    notes: 'En attente de confirmation du chef',
    platforms: ['youtube'],
    created_at: '2026-03-18T09:00:00Z',
  },
  {
    id: 13,
    title: 'Review du pire resto de Paris',
    format_tag: 'review',
    is_long_form: true,
    planned_date: '2026-03-10',
    status: 'published',
    youtube_video_id: 'jkl012',
    notes: null,
    platforms: ['youtube'],
    created_at: '2026-03-02T10:00:00Z',
  },
  {
    id: 14,
    title: 'Gateau a 5EUR vs gateau a 500EUR',
    format_tag: 'challenge',
    is_long_form: true,
    planned_date: null,
    status: 'idea',
    youtube_video_id: null,
    notes: 'Concept a developper',
    platforms: ['youtube', 'tiktok'],
    created_at: '2026-03-19T15:00:00Z',
  },
  {
    id: 15,
    title: 'Croissant geant pour 100 personnes',
    format_tag: 'event',
    is_long_form: true,
    planned_date: '2026-04-15',
    status: 'planned',
    youtube_video_id: null,
    notes: 'Event en partenariat avec la boulangerie du coin',
    platforms: ['youtube', 'instagram'],
    created_at: '2026-03-20T10:00:00Z',
  },
  {
    id: 16,
    title: 'Je mange que du violet pendant 24h',
    format_tag: 'challenge',
    is_long_form: false,
    planned_date: '2026-03-25',
    status: 'filmed',
    youtube_video_id: null,
    notes: 'Tournage OK, montage a faire',
    platforms: ['youtube', 'tiktok'],
    created_at: '2026-03-17T14:00:00Z',
  },
  {
    id: 17,
    title: 'Recette annulee - Sushi geant',
    format_tag: 'tuto',
    is_long_form: true,
    planned_date: '2026-03-14',
    status: 'cancelled',
    youtube_video_id: null,
    notes: 'Annule : probleme de fournisseur poisson',
    platforms: ['youtube'],
    created_at: '2026-03-06T10:00:00Z',
  },
  {
    id: 18,
    title: 'Mes 5 recettes TikTok preferees',
    format_tag: 'reaction',
    is_long_form: false,
    planned_date: '2026-03-30',
    status: 'scheduled',
    youtube_video_id: null,
    notes: 'Programme pour lundi 30',
    platforms: ['youtube', 'tiktok', 'instagram'],
    created_at: '2026-03-21T09:00:00Z',
  },
]
