import type { Sponsor } from '@/types/database'

export const mockSponsors: Sponsor[] = [
  {
    id: 1,
    brand_name: 'NordVPN',
    contact_name: 'Marie Dupont',
    contact_email: 'marie@nordvpn.com',
    sector: 'Tech',
    status: 'paid',
    deal_type: 'integration',
    amount: 4500,
    video_id: 'abc123',
    notes: 'Intégration 60s dans la vidéo gaming',
    created_at: '2025-12-01T10:00:00Z',
  },
  {
    id: 2,
    brand_name: 'HelloFresh',
    contact_name: 'Lucas Martin',
    contact_email: 'lucas@hellofresh.fr',
    sector: 'Alimentaire',
    status: 'delivered',
    deal_type: 'dedicated',
    amount: 5000,
    video_id: 'def456',
    notes: 'Vidéo dédiée recette',
    created_at: '2026-01-15T09:00:00Z',
  },
  {
    id: 3,
    brand_name: 'Deliveroo',
    contact_name: 'Sophie Leroy',
    contact_email: 'sophie@deliveroo.fr',
    sector: 'Alimentaire',
    status: 'signed',
    deal_type: 'integration',
    amount: 3000,
    video_id: null,
    notes: 'Intégration challenge livraison',
    created_at: '2026-02-01T14:00:00Z',
  },
  {
    id: 4,
    brand_name: 'Samsung',
    contact_name: 'Thomas Blanc',
    contact_email: 'thomas@samsung.fr',
    sector: 'Tech',
    status: 'negotiating',
    deal_type: 'dedicated',
    amount: 4000,
    video_id: null,
    notes: 'Unboxing Galaxy S26',
    created_at: '2026-02-10T11:00:00Z',
  },
  {
    id: 5,
    brand_name: 'Nike',
    contact_name: 'Emma Petit',
    contact_email: 'emma@nike.com',
    sector: 'Sport',
    status: 'contacted',
    deal_type: 'barter',
    amount: 1500,
    video_id: null,
    notes: 'Échange produits + placement',
    created_at: '2026-02-20T08:00:00Z',
  },
  {
    id: 6,
    brand_name: 'Decathlon',
    contact_name: 'Hugo Moreau',
    contact_email: 'hugo@decathlon.fr',
    sector: 'Sport',
    status: 'lead',
    deal_type: null,
    amount: 2000,
    video_id: null,
    notes: 'Prospect via agence',
    created_at: '2026-03-01T10:00:00Z',
  },
  {
    id: 7,
    brand_name: 'Leclerc',
    contact_name: 'Camille Roux',
    contact_email: 'camille@leclerc.fr',
    sector: 'Alimentaire',
    status: 'signed',
    deal_type: 'affiliate',
    amount: 800,
    video_id: null,
    notes: 'Lien affilié courses en ligne',
    created_at: '2026-03-05T09:30:00Z',
  },
  {
    id: 8,
    brand_name: 'Action',
    contact_name: 'Julie Bernard',
    contact_email: 'julie@action.fr',
    sector: 'Lifestyle',
    status: 'paid',
    deal_type: 'integration',
    amount: 2500,
    video_id: 'ghi789',
    notes: 'Haul Action intégration 45s',
    created_at: '2025-11-15T10:00:00Z',
  },
  {
    id: 9,
    brand_name: 'Tefal',
    contact_name: 'Antoine Garcia',
    contact_email: 'antoine@tefal.fr',
    sector: 'Lifestyle',
    status: 'negotiating',
    deal_type: 'dedicated',
    amount: 3500,
    video_id: null,
    notes: 'Vidéo dédiée nouvelle gamme',
    created_at: '2026-03-10T15:00:00Z',
  },
  {
    id: 10,
    brand_name: 'Moulinex',
    contact_name: 'Clara Dubois',
    contact_email: 'clara@moulinex.fr',
    sector: 'Lifestyle',
    status: 'contacted',
    deal_type: 'integration',
    amount: 500,
    video_id: null,
    notes: 'Premier contact email',
    created_at: '2026-03-15T12:00:00Z',
  },
]

export interface RevenueMonth {
  month: string
  adsense: number
  sponsors: number
  affiliation: number
}

export const revenueData: RevenueMonth[] = [
  { month: 'Oct', adsense: 1800, sponsors: 2500, affiliation: 400 },
  { month: 'Nov', adsense: 2200, sponsors: 4500, affiliation: 550 },
  { month: 'Dec', adsense: 2600, sponsors: 3000, affiliation: 620 },
  { month: 'Jan', adsense: 1900, sponsors: 5000, affiliation: 480 },
  { month: 'Fev', adsense: 2100, sponsors: 3800, affiliation: 700 },
  { month: 'Mar', adsense: 2400, sponsors: 7500, affiliation: 800 },
]
