import type { Sponsor } from '@/types/database'

// Sponsors réalistes pour un créateur food FR à 543K abonnés
// Tarifs : intégration 60s = €3K-6K | vidéo dédiée = €8K-15K | affiliation = €800-2K/mois
export const mockSponsors: Sponsor[] = [
  {
    id: 1,
    brand_name: 'HelloFresh',
    contact_name: 'Lucas Martin',
    contact_email: 'lucas.martin@hellofresh.fr',
    sector: 'Alimentaire',
    status: 'paid',
    deal_type: 'dedicated',
    amount: 12_000,
    video_id: 'v004',
    notes: 'Vidéo dédiée "3 recettes HelloFresh en mode BATTELLS" — livrée et payée',
    created_at: '2025-11-15T10:00:00Z',
  },
  {
    id: 2,
    brand_name: 'Tefal',
    contact_name: 'Antoine Garcia',
    contact_email: 'antoine.garcia@tefal.fr',
    sector: 'Cuisine',
    status: 'paid',
    deal_type: 'integration',
    amount: 5_500,
    video_id: 'v006',
    notes: 'Intégration 60s dans la vidéo croissant — placement produit Ingenio',
    created_at: '2025-12-01T09:00:00Z',
  },
  {
    id: 3,
    brand_name: 'Uber Eats',
    contact_name: 'Sophie Leroy',
    contact_email: 'sophie.leroy@uber.com',
    sector: 'Livraison',
    status: 'delivered',
    deal_type: 'integration',
    amount: 6_000,
    video_id: 'v016',
    notes: 'Intégration "commande surprise" dans vidéo sandwich Paris',
    created_at: '2026-01-20T14:00:00Z',
  },
  {
    id: 4,
    brand_name: 'Thermomix',
    contact_name: 'Clara Dubois',
    contact_email: 'clara.dubois@vorwerk.fr',
    sector: 'Cuisine',
    status: 'signed',
    deal_type: 'dedicated',
    amount: 15_000,
    video_id: null,
    notes: 'Vidéo dédiée "Mon avis HONNÊTE sur le Thermomix" — tournage prévu semaine 14',
    created_at: '2026-02-10T11:00:00Z',
  },
  {
    id: 5,
    brand_name: 'NordVPN',
    contact_name: 'Marie Dupont',
    contact_email: 'marie.dupont@nordvpn.com',
    sector: 'Tech',
    status: 'signed',
    deal_type: 'integration',
    amount: 4_500,
    video_id: null,
    notes: 'Intégration 60s dans la prochaine vidéo voyage food',
    created_at: '2026-02-28T08:00:00Z',
  },
  {
    id: 6,
    brand_name: 'Leclerc',
    contact_name: 'Camille Roux',
    contact_email: 'camille.roux@leclerc.fr',
    sector: 'Grande distribution',
    status: 'signed',
    deal_type: 'affiliate',
    amount: 1_800,
    video_id: null,
    notes: 'Lien affilié courses en ligne — commission mensuelle ~€1.8K',
    created_at: '2026-03-01T09:30:00Z',
  },
  {
    id: 7,
    brand_name: 'Samsung',
    contact_name: 'Thomas Blanc',
    contact_email: 'thomas.blanc@samsung.fr',
    sector: 'Tech',
    status: 'negotiating',
    deal_type: 'dedicated',
    amount: 10_000,
    video_id: null,
    notes: 'Vidéo "Je filme ma recette avec le Galaxy S26" — négo en cours',
    created_at: '2026-03-05T11:00:00Z',
  },
  {
    id: 8,
    brand_name: 'Deliveroo',
    contact_name: 'Emma Petit',
    contact_email: 'emma.petit@deliveroo.fr',
    sector: 'Livraison',
    status: 'negotiating',
    deal_type: 'integration',
    amount: 5_000,
    video_id: null,
    notes: 'Challenge livraison mystère — discussion sur le brief',
    created_at: '2026-03-10T15:00:00Z',
  },
  {
    id: 9,
    brand_name: 'KitchenAid',
    contact_name: 'Hugo Moreau',
    contact_email: 'hugo.moreau@kitchenaid.fr',
    sector: 'Cuisine',
    status: 'contacted',
    deal_type: 'barter',
    amount: 3_000,
    video_id: null,
    notes: 'Envoi robot Artisan + intégration — premier contact',
    created_at: '2026-03-15T10:00:00Z',
  },
  {
    id: 10,
    brand_name: 'Picard',
    contact_name: 'Julie Bernard',
    contact_email: 'julie.bernard@picard.fr',
    sector: 'Alimentaire',
    status: 'lead',
    deal_type: null,
    amount: 8_000,
    video_id: null,
    notes: 'Prospect via agence Influence4You — vidéo dégustation surgelés',
    created_at: '2026-03-18T12:00:00Z',
  },
  {
    id: 11,
    brand_name: 'Carrefour',
    contact_name: 'Nicolas Faure',
    contact_email: 'nicolas.faure@carrefour.fr',
    sector: 'Grande distribution',
    status: 'lead',
    deal_type: null,
    amount: 7_000,
    video_id: null,
    notes: 'Contact entrant — campagne "Manger Mieux" Q2 2026',
    created_at: '2026-03-20T09:00:00Z',
  },
]

export interface RevenueMonth {
  month: string
  adsense: number
  sponsors: number
  affiliation: number
}

// Revenus mensuels réalistes pour 543K subs food FR
// AdSense : €12K-22K | Sponsors : €5K-15K | Affiliation : €800-2K
export const revenueData: RevenueMonth[] = [
  { month: 'Oct', adsense: 14_200, sponsors: 5_500, affiliation: 950 },
  { month: 'Nov', adsense: 16_800, sponsors: 12_000, affiliation: 1_200 },
  { month: 'Dec', adsense: 21_500, sponsors: 6_000, affiliation: 1_450 },
  { month: 'Jan', adsense: 15_600, sponsors: 12_000, affiliation: 1_100 },
  { month: 'Fev', adsense: 17_300, sponsors: 11_500, affiliation: 1_600 },
  { month: 'Mar', adsense: 18_460, sponsors: 15_000, affiliation: 1_800 },
]
